-- For PostgreSQL Database Schema for SIGMAmed Medication System
-- Create SIGMAmed Schema
CREATE SCHEMA IF NOT EXISTS "SIGMAmed";

-- Set search path to SIGMAmed and public schemas
SET
	SEARCH_PATH TO "SIGMAmed",
	PUBLIC;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- ----------------------------------------------------
--  TRIGGER FUNCTION (Utility Function)
-- ----------------------------------------------------
-- FUNCTION: Auto-create role-specific entry when User is inserted
CREATE OR REPLACE FUNCTION "SIGMAmed".auto_create_role_entry() RETURNS TRIGGER AS $$
BEGIN
    -- Create corresponding role table entry based on user role
    IF NEW."Role" = 'doctor' THEN
        -- Insert placeholder doctor record (will need to be updated later)
        INSERT INTO "SIGMAmed"."Doctor" (
            "UserId",
            "MedicalLicenseNumber",
            "Specialization",
            "YearOfExperience"
        ) VALUES (
            NEW."UserId",
            'TEMP-' || NEW."UserId",  -- Temporary license number
            'General Practice',        -- Default specialization
            0                    -- Default experience
        );
        
        RAISE NOTICE 'Doctor record created for User %. Please update MedicalLicenseNumber, Specialization, and other details.', NEW."UserId";
        
    ELSIF NEW."Role" = 'patient' THEN
        -- PatientNumber will be auto-generated by trigger_generate_patient_number
        -- Leave PatientNumber empty/null, the BEFORE INSERT trigger on Patient will set it
        INSERT INTO "SIGMAmed"."Patient" (
            "UserId",
            "PatientNumber",
            "BloodType",
            "HeightCm",
            "WeightKg",
            "EmergencyContactName",
            "EmergencyContactNumber",
            "MedicationAllergies"
        ) VALUES (
            NEW."UserId",
            '',  -- Will be set by trigger_generate_patient_number
            NULL,
            0,
            0,
            ' ',
            ' ',
            '[]'::JSONB
        );
        
        RAISE NOTICE 'Patient record created for User %. Patient number will be auto-generated.', NEW."UserId";
        
    ELSIF NEW."Role" = 'admin' THEN
        INSERT INTO "SIGMAmed"."Admin" (
            "UserId",
            "AdminLevel"
        ) VALUES (
            NEW."UserId",
            'hospital'  -- Default to hospital admin level
        );
        
        RAISE NOTICE 'Admin record created for User % with hospital level access.', NEW."UserId";
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".auto_create_role_entry IS 'Automatically create Doctor/Patient/Admin entry when User is created';

-- FUNCTION: Auto-generate Patient Number
CREATE OR REPLACE FUNCTION "SIGMAmed".generate_patient_number() RETURNS TRIGGER AS $$
DECLARE
    v_year TEXT;
    v_patient_number TEXT;
    v_counter INT;
BEGIN
    -- Generate patient number if it's NULL or empty string
    IF NEW."PatientNumber" IS NULL OR NEW."PatientNumber" = '' THEN
        v_year := TO_CHAR(CURRENT_DATE, 'YYYY');
        
        -- Get next sequence using pg_advisory_xact_lock for thread safety during bulk inserts
        PERFORM pg_advisory_xact_lock(hashtext('patient_number_seq_' || v_year));
        
        -- Get the maximum sequence number for this year
        SELECT COALESCE(MAX(
            CAST(SUBSTRING("PatientNumber" FROM 10 FOR 6) AS INT)
        ), 0) + 1
        INTO v_counter
        FROM "SIGMAmed"."Patient"
        WHERE "PatientNumber" ~ ('^PAT-' || v_year || '-[0-9]{6}$');
        
        v_patient_number := 'PAT-' || v_year || '-' || LPAD(v_counter::TEXT, 6, '0');
        NEW."PatientNumber" := v_patient_number;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".generate_patient_number IS 'Automatically generate the patient number of patients.';

-- FUNCTION: Prevent to delete the active prescription
CREATE OR REPLACE FUNCTION "SIGMAmed".prevent_delete_active_prescription() RETURNS TRIGGER AS $$
BEGIN
    IF OLD."Status" = 'active' AND NEW."IsDeleted" = TRUE THEN
        RAISE EXCEPTION 'Cannot delete active prescription. Please complete or cancel first.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".prevent_delete_active_prescription IS 'Prevent deleting the active prescriptions.';

-- FUNCTION: Prevent past appointment creation 
CREATE OR REPLACE FUNCTION "SIGMAmed".prevent_past_appointments() RETURNS TRIGGER AS $$
BEGIN
    IF NEW."AppointmentDate" < CURRENT_DATE THEN
        RAISE EXCEPTION 'Cannot create appointment in the past';
    END IF;
    
    IF NEW."AppointmentDate" = CURRENT_DATE THEN
        RAISE EXCEPTION 'Cannot create appointment in the past';
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".prevent_past_appointments IS 'Prevent past appointment creation.';

-- FUNCTION: Notify doctor when new patient reports comes in
CREATE OR REPLACE FUNCTION "SIGMAmed".notify_extract_keyword() RETURNS TRIGGER AS $$
BEGIN
    -- Only notify if Description is not null and Keywords still null
    IF NEW."Description" IS NOT NULL AND NEW."Keywords" IS NULL THEN
        PERFORM pg_notify('report_ready_for_processing', NEW."PatientReportId"::text);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".notify_extract_keyword IS 'Notify doctor when new patient reports comes in.';

-- FUNCTION: Auto create the prescribed medication schedule record in Prescribed Medication schedule
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_generate_medication_schedule() RETURNS TRIGGER AS $$
DECLARE
    interval_value INTERVAL;
    times_per_day INT;
    i INT;
    base_time TIME := TIME '08:00:00';
    next_time TIME;
BEGIN
    interval_value := NEW."DoseInterval";
    times_per_day := NEW."TimesPerDay";

    next_time := base_time;
    FOR i IN 1..times_per_day LOOP
        INSERT INTO "SIGMAmed"."PrescribedMedicationSchedule"(
            "PrescribedMedicationId",
            "ReminderTime",
            "DayOfWeekMask",
            "DoseSequenceId"
        )
        VALUES(
            NEW."PrescribedMedicationId",
            next_time,
            NEW."DefaultDayMask",
            i
        );
        next_time := (next_time + interval_value);
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".fn_generate_medication_schedule IS 'Auto create the prescribed medication schedule record in Prescribed Medication schedule.';

-- FUNCTION: Auto create the adherence record in Medication adherence 
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_create_adherence_record() RETURNS TRIGGER AS $$
DECLARE 
    prescribed_date DATE;
    expiry_date DATE;
    mask TEXT;
    day_index INT;
    check_date DATE;
    scheduled_timestamp TIMESTAMPTZ;
    v_prescription_id UUID;
BEGIN 
    -- Get prescribed_date + day mask + prescription id from PrescribedMedication
    SELECT 
        "PrescribedDate",
        "DefaultDayMask",
        "PrescriptionId"
    INTO 
        prescribed_date,
        mask,
        v_prescription_id
    FROM "SIGMAmed"."PrescribedMedication"
    WHERE "PrescribedMedicationId" = NEW."PrescribedMedicationId";

    -- Get expiry date from Prescription table
    SELECT "ExpiryDate"
    INTO expiry_date
    FROM "SIGMAmed"."Prescription"
    WHERE "PrescriptionId" = v_prescription_id;

    check_date := prescribed_date;

    -- DAILY LOOP UNTIL EXPIRY DATE
    WHILE check_date <= expiry_date LOOP
        
        day_index := EXTRACT(DOW FROM check_date)::INT;
        IF day_index = 0 THEN
            day_index := 7;
        END IF;

        -- If mask = '1' for this day, insert adherence record
        IF SUBSTRING(mask FROM day_index FOR 1) = '1' THEN
            scheduled_timestamp := check_date + NEW."ReminderTime";
            
            IF scheduled_timestamp > CURRENT_TIMESTAMP THEN
            INSERT INTO "SIGMAmed"."MedicationAdherenceRecord"(
                "PrescribedMedicationScheduleId",
                "DoseQuantity",
                "ScheduledTime"
            )
            VALUES(
                NEW."PrescribedMedicationScheduleId",
                NULL,
                scheduled_timestamp
            );
            END IF;
        END IF;

        check_date := check_date + INTERVAL '1 day';
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".fn_create_adherence_record IS 'Auto create the adherence record in Medication adherence.';

-- FUNCTION: Delete all old adherence
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_delete_old_adherence() RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM "SIGMAmed"."MedicationAdherenceRecord"
    WHERE "PrescribedMedicationScheduleId" = OLD."PrescribedMedicationScheduleId" AND "CurrentStatus" = 'Pending' AND "ScheduledTime" > NOW();

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".fn_create_adherence_record IS 'Delete all old adherence records in MedicationAdherenceRecordTable.';

-- FUNCTION: Create the adherence record based on new day of week mask
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_create_adherence_after_change() RETURNS TRIGGER AS $$
DECLARE
    prescribed_date DATE;
    expiry_date DATE;
    day_index INT;
    check_date DATE;
    scheduled_timestamp TIMESTAMPTZ;
    prescription_id UUID;
    mask TEXT;
BEGIN
    -- Get schedule mask
    mask := NEW."DayOfWeekMask";

    -- Get prescription data
    SELECT 
        "PrescribedDate",
        "PrescriptionId"
    INTO
        prescribed_date,
        prescription_id
    FROM "SIGMAmed"."PrescribedMedication"
    WHERE "PrescribedMedicationId" = NEW."PrescribedMedicationId";

    -- Get expiry date
    SELECT "ExpiryDate"
    INTO expiry_date
    FROM "SIGMAmed"."Prescription"
    WHERE "PrescriptionId" = prescription_id;

    check_date := prescribed_date;

    -- Recreate adherence records
    WHILE check_date <= expiry_date LOOP
        day_index := EXTRACT(DOW FROM check_date);

        IF day_index = 0 THEN
            day_index := 7;
        END IF;

        IF SUBSTRING(mask FROM day_index FOR 1) = '1' THEN
            scheduled_timestamp := check_date + NEW."ReminderTime";

            INSERT INTO "SIGMAmed"."MedicationAdherenceRecord"(
                "PrescribedMedicationScheduleId",
                "DoseQuantity",
                "ScheduledTime"
            ) VALUES (
                NEW."PrescribedMedicationScheduleId",
                NULL,
                scheduled_timestamp
            );
        END IF;

        check_date := check_date + INTERVAL '1 day';
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".fn_create_adherence_after_change IS 'Create the adherence record based on new day of week mask.';

-- FUNCTION: Delete the related record in prescribed medication schedule table 
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_rebuild_schedule_on_mask_change()
RETURNS TRIGGER AS $$
DECLARE
    interval_value INTERVAL;
    times_per_day INT;
    i INT;
    base_time TIME := TIME '08:00:00';
    next_time TIME;
BEGIN
    IF NEW."DefaultDayMask" IS DISTINCT FROM OLD."DefaultDayMask" THEN

        -- 1. Delete schedule records
        DELETE FROM "SIGMAmed"."PrescribedMedicationSchedule"
        WHERE "PrescribedMedicationId" = NEW."PrescribedMedicationId";
        
        interval_value := NEW."DoseInterval";
        times_per_day := NEW."TimesPerDay";
        -- Recreate prescribedmedicationschedule 
        next_time := base_time;
        FOR i IN 1..times_per_day LOOP
            INSERT INTO "SIGMAmed"."PrescribedMedicationSchedule"(
                "PrescribedMedicationId",
                "ReminderTime",
                "DayOfWeekMask",
                "DoseSequenceId"
            )
            VALUES(
                NEW."PrescribedMedicationId",
                next_time,
                NEW."DefaultDayMask",
                i
            );
            next_time := (next_time + interval_value);
        END LOOP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
COMMENT ON FUNCTION "SIGMAmed".fn_rebuild_schedule_on_mask_change IS 'Delete the related record in prescribed medication schedule table.';

-- FUNCTION: Create record inside appointment reminder table 
CREATE OR REPLACE FUNCTION "SIGMAmed".fn_generate_appointment_reminders() RETURNS TRIGGER AS $$
BEGIN
    -- Insert reminder 1 day before
    INSERT INTO "SIGMAmed"."AppointmentReminder"(
        "AppointmentId",
        "ScheduledTime"
    ) VALUES (
        NEW."AppointmentId",
        NEW."AppointmentDate" - INTERVAL '1 day'
    );

    -- Insert reminder 1 hour before
    INSERT INTO "SIGMAmed"."AppointmentReminder"(
        "AppointmentId",
        "ScheduledTime"
    ) VALUES (
        NEW."AppointmentId",
        NEW."AppointmentDate" - INTERVAL '1 hour'
    );

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".fn_generate_appointment_reminders IS 'Create record inside appointment reminder table.';

-- FUNCTION: Send listener to channel for newly insert patient report record
CREATE OR REPLACE FUNCTION "SIGMAmed".notify_new_patient_report() RETURNS TRIGGER AS $$
BEGIN
    -- Only notify if VoiceDirectory is NOT NULL and keyword IS NULL
    IF NEW."VoiceDirectory" IS NOT NULL AND (NEW."Description" IS NULL OR NEW."Description" = '') AND NEW."Keywords" IS NULL THEN
        PERFORM pg_notify(
            'new_patient_report', 
            json_build_object(
                'voice_path', NEW."VoiceDirectory",
                'report_id', NEW."PatientReportId"
            )::text
        );
    ELSIF NEW."Description" IS NOT NULL AND NEW."Keywords" IS NULL THEN
        PERFORM pg_notify('new_desc_patient_report',NEW."PatientReportId"::text);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION "SIGMAmed".notify_new_patient_report IS 'Send listener to channel for newly insert patient report record.';

-- FUNCTION: Automatically sets the "UpdatedAt" column to the current timestamp on update
CREATE OR REPLACE FUNCTION public.set_updated_at_timestamp() RETURNS TRIGGER AS $$
BEGIN
    -- Check if UpdatedAt column exists in the table structure before setting
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = TG_TABLE_SCHEMA
        AND table_name = TG_TABLE_NAME
        AND column_name = 'UpdatedAt'
    ) THEN
        NEW."UpdatedAt" = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

COMMENT ON FUNCTION public.set_updated_at_timestamp () IS 'Automatically sets the "UpdatedAt" column to the current timestamp on update.';

-- FUNCTION: Capture the User id and record id to insert inside the audit log table
CREATE OR REPLACE FUNCTION "SIGMAmed".audit_log_capture_function() RETURNS TRIGGER AS $$
DECLARE
    v_old_data JSONB;
    v_new_data JSONB;
    v_record_id UUID;
	v_action_status "SIGMAmed".action_type_enum;
    
    -- The fallback ID must exist in the "SIGMAmed"."User" table (e.g., the 'system_audit' user).
    SYSTEM_FALLBACK_ID CONSTANT UUID := '00000000-0000-0000-0000-000000000000';
    
    -- Variable to hold the final ActedBy ID
    v_acted_by UUID; 
BEGIN
    -- 1. Get the ActedBy User ID
    -- Safely read the 'app.current_user_id' session variable (set by the application). 
    -- If the session variable is not set (TRUE prevents error) or is an empty string, 
    -- COALESCE falls back to the defined SYSTEM_FALLBACK_ID.
    v_acted_by := COALESCE(
        NULLIF(current_setting('app.current_user_id', TRUE), '')::UUID,
        SYSTEM_FALLBACK_ID
    );
    
    -- 2. Determine old/new data and find the RecordId based on the operation
    IF (TG_OP = 'DELETE') THEN
    -- ... (rest of the logic remains the same) ...
        v_action_status := 'delete';
        v_old_data = to_jsonb(OLD);
        v_new_data = '[]'::jsonb;
        
    ELSIF (TG_OP = 'INSERT') THEN
        v_action_status := 'insert';
        v_old_data = '[]'::jsonb;
        v_new_data = to_jsonb(NEW);
        
    ELSIF (TG_OP = 'UPDATE') THEN
        v_action_status := 'update';
        v_old_data = to_jsonb(OLD);
        v_new_data = to_jsonb(NEW);
        
    ELSE
        RETURN NULL; 
    END IF;

    -- 3. Dynamically extract the Primary Key (RecordId)
    v_record_id = COALESCE(
        v_new_data ->> (REPLACE(TG_TABLE_NAME, 'Id', '') || 'Id'), -- Tries to find 'TableNameId'
        v_new_data ->> 'UserId', -- Tries to find 'UserId'
        v_old_data ->> (REPLACE(TG_TABLE_NAME, 'Id', '') || 'Id'),
        v_old_data ->> 'UserId'
    )::UUID;

    -- 4. Insert the audit record into the AuditLog table
    INSERT INTO "SIGMAmed"."AuditLog" ("ActedBy", "TableName", "RecordId", "ActionStatus", "OldValue", "NewValue")
    VALUES (
        v_acted_by, 
        TG_TABLE_NAME, 
        v_record_id, 
        v_action_status, 
        v_old_data, 
        v_new_data
    );

    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

COMMENT ON FUNCTION "SIGMAmed".audit_log_capture_function () IS 'Capture the User id and record id to insert inside the audit log table.';

-- ----------------------------------------------------
--  CREATE TABLES (The Main Structure)
-- ----------------------------------------------------
-- Table 1: ClinicalInstitution
CREATE TABLE IF NOT EXISTS "SIGMAmed"."ClinicalInstitution" (
	"ClinicalInstitutionId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"ClinicalInstitutionName" VARCHAR(100) NOT NULL,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 2: Medication
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Medication" (
	"MedicationId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"ClinicalInstitutionId" UUID NULL REFERENCES "SIGMAmed"."ClinicalInstitution" ("ClinicalInstitutionId") ON DELETE SET NULL,
	"MedicationName" VARCHAR(100) NOT NULL,
	"Unit" VARCHAR(50) NULL,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"DosageForm" "SIGMAmed".dosage_form_enum,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE ("ClinicalInstitutionId", "MedicationName")
);

-- Table 3: User
CREATE TABLE IF NOT EXISTS "SIGMAmed"."User" (
	"UserId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"ClinicalInstitutionId" UUID NULL REFERENCES "SIGMAmed"."ClinicalInstitution" ("ClinicalInstitutionId") ON DELETE RESTRICT,
	"Username" VARCHAR(50) UNIQUE NOT NULL,
	"Email" CITEXT UNIQUE NOT NULL,
	"PasswordHash" VARCHAR(255) NOT NULL,
	"Role" "SIGMAmed".user_role_enum NOT NULL,
	"ICPassportNumber" VARCHAR(50) UNIQUE NOT NULL,
	"FirstName" VARCHAR(100) NOT NULL,
	"LastName" VARCHAR(100) NOT NULL,
	"Phone" VARCHAR(20) NOT NULL,
	"DateOfBirth" DATE NOT NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT CHK_USER_AGE CHECK (DATE_PART('year', AGE ("DateOfBirth")) >= 0),
	CONSTRAINT CHK_EMAIL_FORMAT CHECK (
		"Email" ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
	)
);

-- Table 4: AuditLog
CREATE TABLE IF NOT EXISTS "SIGMAmed"."AuditLog" (
	"AuditLogId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"ActedBy" UUID REFERENCES "SIGMAmed"."User" ("UserId") NOT NULL,
	"ActionTimestamp" TIMESTAMPTZ DEFAULT NOW(),
	"TableName" VARCHAR(75) NOT NULL,
	"RecordId" UUID NOT NULL,
	"ActionStatus" "SIGMAmed".action_type_enum NOT NULL,
	"OldValue" JSONB DEFAULT '[]'::JSONB,
	"NewValue" JSONB DEFAULT '[]'::JSONB
);

-- Table 5: Admin
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Admin" (
	"UserId" UUID PRIMARY KEY REFERENCES "SIGMAmed"."User" ("UserId") ON DELETE CASCADE,
	"AdminLevel" "SIGMAmed".admin_level_enum
);

-- Table 6: Doctor
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Doctor" (
	"UserId" UUID PRIMARY KEY REFERENCES "SIGMAmed"."User" ("UserId") ON DELETE CASCADE,
	"MedicalLicenseNumber" VARCHAR(50) UNIQUE NOT NULL,
	"Specialization" VARCHAR(100) NOT NULL,
	"YearOfExperience" INT NOT NULL,
	CONSTRAINT CHK_EXPERIENCE CHECK (
		"YearOfExperience" >= 0
		AND "YearOfExperience" <= 60
	)
);

-- Table 7: Patient
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Patient" (
	"UserId" UUID PRIMARY KEY REFERENCES "SIGMAmed"."User" ("UserId") ON DELETE CASCADE,
	"PatientNumber" VARCHAR(20) UNIQUE NOT NULL,
	"BloodType" VARCHAR(5) NULL,
	"HeightCm" DECIMAL(5, 2) NOT NULL,
	"WeightKg" DECIMAL(5, 2) NOT NULL,
	"EmergencyContactName" VARCHAR(100) NOT NULL,
	"EmergencyContactNumber" VARCHAR(20) NOT NULL,
	"MedicationAllergies" JSONB DEFAULT '[]',
	CONSTRAINT CHK_BLOOD_TYPE CHECK (
		"BloodType" IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')
		OR "BloodType" IS NULL
	),
	CONSTRAINT CHK_HEIGHT CHECK (
		(
			"HeightCm" > 0
			AND "HeightCm" < 300
		)
		OR "HeightCm" = 0
	),
	CONSTRAINT CHK_WEIGHT CHECK (
		(
			"WeightKg" > 0
			AND "WeightKg" < 500
		)
		OR "WeightKg" = 0
	)
);

-- Table 8: Medical History
CREATE TABLE IF NOT EXISTS "SIGMAmed"."MedicalHistory" (
	"MedicalHistoryId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId") ON DELETE CASCADE,
	"DiseaseName" VARCHAR(100) NOT NULL,
	"Severity" "SIGMAmed".severity_enum DEFAULT 'mild',
	"DiagnosedDate" TIMESTAMPTZ NOT NULL,
	"ResolutionDate" TIMESTAMPTZ NULL,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 9: Patient Symptom
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PatientSymptom" (
	"PatientSymptomId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"MedicalHistoryId" UUID NULL REFERENCES "SIGMAmed"."MedicalHistory" ("MedicalHistoryId"),
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId"),
	"SymptomName" VARCHAR(100) NOT NULL,
	"Severity" "SIGMAmed".severity_enum DEFAULT 'mild',
	"OnsetDate" TIMESTAMPTZ NOT NULL,
	"ResolutionDate" TIMESTAMPTZ NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE ("MedicalHistoryId", "SymptomName")
);

-- Table 10: Patient Care Team
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PatientCareTeam" (
	"PatientCareTeamId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"DoctorId" UUID NOT NULL REFERENCES "SIGMAmed"."Doctor" ("UserId") ON DELETE CASCADE,
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId") ON DELETE CASCADE,
	"DoctorLevel" "SIGMAmed".doctor_level_enum NOT NULL,
	"Role" VARCHAR(50) NULL,
	"IsActive" BOOLEAN DEFAULT TRUE,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	UNIQUE ("DoctorId", "PatientId", "DoctorLevel")
);

-- Table 11: Prescription
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Prescription" (
	"PrescriptionId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"DoctorId" UUID NOT NULL REFERENCES "SIGMAmed"."Doctor" ("UserId") ON DELETE RESTRICT,
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId") ON DELETE CASCADE,
	"PrescriptionNumber" VARCHAR(50) UNIQUE NOT NULL,
	"Status" "SIGMAmed".prescription_status_enum NOT NULL,
	"PrescribedDate" TIMESTAMPTZ NOT NULL,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"ExpiryDate" TIMESTAMPTZ NOT NULL,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 12: Prescribed Medication
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PrescribedMedication" (
	"PrescribedMedicationId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"PrescriptionId" UUID NOT NULL REFERENCES "SIGMAmed"."Prescription" ("PrescriptionId") ON DELETE CASCADE,
	"MedicationId" UUID NOT NULL REFERENCES "SIGMAmed"."Medication" ("MedicationId") ON DELETE RESTRICT,
	"DosageAmountPrescribed" DECIMAL(5, 2) NOT NULL,
	"DosePerTime" DECIMAL(5, 2) NOT NULL,
	"Status" "SIGMAmed".prescribedmedication_status_enum DEFAULT 'active',
	"DefaultDayMask" VARCHAR(7) NOT NULL,
	"DoseInterval" INTERVAL NOT NULL,
	"PrescribedDate" TIMESTAMPTZ NOT NULL,
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"MedicationNameSnapshot" VARCHAR(100) NOT NULL,
	"TimesPerDay" INT NOT NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 13: Patient Side Effect
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PatientSideEffect" (
	"PatientSideEffectId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"PrescribedMedicationId" UUID NOT NULL REFERENCES "SIGMAmed"."PrescribedMedication" ("PrescribedMedicationId") ON DELETE CASCADE,
	"SideEffectName" VARCHAR(100) NOT NULL,
	"Severity" "SIGMAmed".severity_enum DEFAULT 'mild',
	"OnsetDate" TIMESTAMPTZ NOT NULL,
	"ResolutionDate" TIMESTAMPTZ NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT CHK_SIDE_EFFECT_DATES CHECK (
		"ResolutionDate" IS NULL
		OR "OnsetDate" <= "ResolutionDate"
	),
	UNIQUE ("PrescribedMedicationId", "SideEffectName")
);

-- Table 14: Prescribed Medication Schedule
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PrescribedMedicationSchedule" (
	"PrescribedMedicationScheduleId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"PrescribedMedicationId" UUID NOT NULL REFERENCES "SIGMAmed"."PrescribedMedication" ("PrescribedMedicationId") ON DELETE CASCADE,
	"ReminderTime" TIME NOT NULL,
	"DayOfWeekMask" VARCHAR(7) NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"DoseSequenceId" INT NOT NULL
);

-- Table 15: Medication Adherence Record
CREATE TABLE IF NOT EXISTS "SIGMAmed"."MedicationAdherenceRecord" (
	"MedicationAdherenceRecordId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"PrescribedMedicationScheduleId" UUID NULL REFERENCES "SIGMAmed"."PrescribedMedicationSchedule" ("PrescribedMedicationScheduleId") ON DELETE CASCADE,
	"CurrentStatus" "SIGMAmed".reminder_status_enum DEFAULT 'Pending',
	"DoseQuantity" DECIMAL(5, 2) NULL,
	"ScheduledTime" TIMESTAMPTZ NOT NULL,
	"ActionTime" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 16: Patient Report
CREATE TABLE IF NOT EXISTS "SIGMAmed"."PatientReport" (
	"PatientReportId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"DoctorId" UUID NOT NULL REFERENCES "SIGMAmed"."Doctor" ("UserId") ON DELETE RESTRICT,
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId") ON DELETE CASCADE,
	"PrescribedMedicationId" UUID NULL REFERENCES "SIGMAmed"."PrescribedMedication" ("PrescribedMedicationId"),
	"Type" "SIGMAmed".patient_report_status_enum NULL,
	"Description" TEXT NULL,
	"Keywords" TEXT NULL,
	"VoiceDirectory" TEXT NULL,
	"DoctorNote" TEXT NULL,
	"Severity" "SIGMAmed".severity_enum DEFAULT 'mild',
	"ReviewTime" TIMESTAMPTZ NULL,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"IsDeleted" BOOLEAN DEFAULT FALSE
);

-- Table 17: Appointment
CREATE TABLE IF NOT EXISTS "SIGMAmed"."Appointment" (
	"AppointmentId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"DoctorId" UUID NOT NULL REFERENCES "SIGMAmed"."Doctor" ("UserId") ON DELETE RESTRICT,
	"PatientId" UUID NOT NULL REFERENCES "SIGMAmed"."Patient" ("UserId") ON DELETE CASCADE,
	"AppointmentDate" TIMESTAMPTZ NOT NULL,
	"AppointmentType" "SIGMAmed".appointment_type_enum NOT NULL,
	"Status" "SIGMAmed".appointment_status_enum DEFAULT 'scheduled',
	"IsDeleted" BOOLEAN DEFAULT FALSE,
	"UpdatedAt" TIMESTAMPTZ DEFAULT NOW(),
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Table 18: Appointment Reminder
CREATE TABLE IF NOT EXISTS "SIGMAmed"."AppointmentReminder" (
	"AppointmentReminderId" UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
	"AppointmentId" UUID NULL REFERENCES "SIGMAmed"."Appointment" ("AppointmentId"),
	"ScheduledTime" TIMESTAMPTZ NOT NULL,
	"CreatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------
-- 5. APPLY TRIGGERS (Must be last)
-- ----------------------------------------------------
CREATE TRIGGER trigger_auto_create_role_entry
AFTER INSERT ON "SIGMAmed"."User" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".auto_create_role_entry ();

CREATE TRIGGER trigger_generate_patient_number BEFORE INSERT ON "SIGMAmed"."Patient" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".generate_patient_number ();

CREATE TRIGGER trigger_prevent_delete_active_prescription BEFORE
UPDATE OF "IsDeleted" ON "SIGMAmed"."Prescription" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".prevent_delete_active_prescription ();

CREATE TRIGGER trigger_prevent_past_appointments BEFORE INSERT ON "SIGMAmed"."Appointment" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".prevent_past_appointments ();

CREATE TRIGGER patient_report_update_trigger
AFTER
UPDATE OF "Description" ON "SIGMAmed"."PatientReport" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".notify_extract_keyword ();

CREATE TRIGGER trg_after_prescribed_med_insert
AFTER INSERT ON "SIGMAmed"."PrescribedMedication" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_generate_medication_schedule ();

CREATE TRIGGER trg_after_insert_schedule
AFTER INSERT ON "SIGMAmed"."PrescribedMedicationSchedule" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_create_adherence_record ();

CREATE TRIGGER trg_before_update_delete_adherence BEFORE
UPDATE ON "SIGMAmed"."PrescribedMedicationSchedule" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_delete_old_adherence ();

CREATE TRIGGER trg_after_insert_update_create_adherence
AFTER INSERT
OR
UPDATE ON "SIGMAmed"."PrescribedMedicationSchedule" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_create_adherence_after_change ();

CREATE TRIGGER trg_after_mask_update
AFTER
UPDATE OF "DefaultDayMask" ON "SIGMAmed"."PrescribedMedication" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_rebuild_schedule_on_mask_change ();

CREATE TRIGGER trg_after_appointment_insert
AFTER INSERT ON "SIGMAmed"."Appointment" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".fn_generate_appointment_reminders ();

CREATE TRIGGER patient_report_insert_trigger
AFTER INSERT ON "SIGMAmed"."PatientReport" FOR EACH ROW
EXECUTE FUNCTION "SIGMAmed".notify_new_patient_report ();

CREATE TRIGGER set_updated_at_ClinicalInstitution
BEFORE UPDATE ON "SIGMAmed"."ClinicalInstitution"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_Medication
BEFORE UPDATE ON "SIGMAmed"."Medication"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_User
BEFORE UPDATE ON "SIGMAmed"."User"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_MedicalHistory
BEFORE UPDATE ON "SIGMAmed"."MedicalHistory"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PatientSymptom
BEFORE UPDATE ON "SIGMAmed"."PatientSymptom"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PatientCareTeam
BEFORE UPDATE ON "SIGMAmed"."PatientCareTeam"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_Prescription
BEFORE UPDATE ON "SIGMAmed"."Prescription"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PrescribedMedication
BEFORE UPDATE ON "SIGMAmed"."PrescribedMedication"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PatientSideEffect
BEFORE UPDATE ON "SIGMAmed"."PatientSideEffect"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PrescribedMedicationSchedule
BEFORE UPDATE ON "SIGMAmed"."PrescribedMedicationSchedule"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_PatientReport
BEFORE UPDATE ON "SIGMAmed"."PatientReport"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE TRIGGER set_updated_at_Appointment
BEFORE UPDATE ON "SIGMAmed"."Appointment"
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp();

-- ----------------------------------------------------
-- 6. APPLY COMBINED AUDIT TRIGGERS 
-- ----------------------------------------------------
-- Table 1: ClinicalInstitution (CI)
CREATE TRIGGER audit_ci_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."ClinicalInstitution"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 2: Medication (Med)
CREATE TRIGGER audit_med_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Medication"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 3: User (Usr)
CREATE TRIGGER audit_usr_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."User"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 5: Admin (Adm)
CREATE TRIGGER audit_adm_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Admin"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 6: Doctor (Doc)
CREATE TRIGGER audit_doc_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Doctor"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 7: Patient (Pnt)
CREATE TRIGGER audit_pnt_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Patient"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 8: Medical History (MH)
CREATE TRIGGER audit_mh_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."MedicalHistory"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 9: Patient Symptom (PSym)
CREATE TRIGGER audit_psym_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."PatientSymptom"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 10: Patient Care Team (PCT)
CREATE TRIGGER audit_pct_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."PatientCareTeam"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 11: Prescription (Presc)
CREATE TRIGGER audit_presc_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Prescription"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 12: Prescribed Medication (PMed)
CREATE TRIGGER audit_pmed_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."PrescribedMedication"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 13: Patient Side Effect (PSE)
CREATE TRIGGER audit_pse_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."PatientSideEffect"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 14: Prescribed Medication Schedule (PMS)
CREATE TRIGGER audit_pms_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."PrescribedMedicationSchedule"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 15: Medication Adherence Record (MAR)
CREATE TRIGGER audit_mar_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."MedicationAdherenceRecord"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 17: Appointment (Appt)
CREATE TRIGGER audit_appt_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."Appointment"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();

-- Table 18: Appointment Reminder (AR)
CREATE TRIGGER audit_ar_all
AFTER INSERT OR UPDATE OR DELETE ON "SIGMAmed"."AppointmentReminder"
FOR EACH ROW EXECUTE FUNCTION "SIGMAmed".audit_log_capture_function();


DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sigmamed_superadmin') THEN
        CREATE ROLE sigmamed_superadmin;
    END IF;
    
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sigmamed_hospital_admin') THEN
        CREATE ROLE sigmamed_hospital_admin;
    END IF;
    
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sigmamed_doctor') THEN
        CREATE ROLE sigmamed_doctor;
    END IF;
    
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sigmamed_patient') THEN
        CREATE ROLE sigmamed_patient;
    END IF;
END
$$;

-- GRANT TABLE PERMISSIONS
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "SIGMAmed" TO sigmamed_superadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "SIGMAmed" TO sigmamed_superadmin;
GRANT ALL PRIVILEGES ON SCHEMA "SIGMAmed" TO sigmamed_superadmin;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."User" TO sigmamed_hospital_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Admin" TO sigmamed_hospital_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Doctor" TO sigmamed_hospital_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Patient" TO sigmamed_hospital_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PatientCareTeam" TO sigmamed_hospital_admin;
GRANT SELECT, UPDATE ON TABLE "SIGMAmed"."ClinicalInstitution" TO sigmamed_hospital_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Medication" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."Appointment" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."AppointmentReminder" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."Prescription" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."PrescribedMedication" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."PrescribedMedicationSchedule" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."MedicationAdherenceRecord" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."MedicalHistory" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."PatientSymptom" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."PatientSideEffect" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."PatientReport" TO sigmamed_hospital_admin;
GRANT SELECT ON TABLE "SIGMAmed"."AuditLog" TO sigmamed_hospital_admin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "SIGMAmed" TO sigmamed_hospital_admin;
GRANT USAGE ON SCHEMA "SIGMAmed" TO sigmamed_hospital_admin;

GRANT SELECT ON TABLE "SIGMAmed"."User" TO sigmamed_doctor;
GRANT SELECT ON TABLE "SIGMAmed"."Doctor" TO sigmamed_doctor;
GRANT SELECT ON TABLE "SIGMAmed"."Patient" TO sigmamed_doctor;
GRANT SELECT ON TABLE "SIGMAmed"."ClinicalInstitution" TO sigmamed_doctor;
GRANT SELECT ON TABLE "SIGMAmed"."Medication" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PatientCareTeam" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Appointment" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."AppointmentReminder" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."Prescription" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PrescribedMedication" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PrescribedMedicationSchedule" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."MedicationAdherenceRecord" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."MedicalHistory" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PatientSymptom" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PatientSideEffect" TO sigmamed_doctor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SIGMAmed"."PatientReport" TO sigmamed_doctor;
GRANT SELECT ON TABLE "SIGMAmed"."AuditLog" TO sigmamed_doctor;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "SIGMAmed" TO sigmamed_doctor;
GRANT USAGE ON SCHEMA "SIGMAmed" TO sigmamed_doctor;

GRANT SELECT ON TABLE "SIGMAmed"."User" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."Patient" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."ClinicalInstitution" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."Medication" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."PatientCareTeam" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."Appointment" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."AppointmentReminder" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."Prescription" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."PrescribedMedication" TO sigmamed_patient;
GRANT SELECT, UPDATE ON TABLE "SIGMAmed"."PrescribedMedicationSchedule" TO sigmamed_patient;
GRANT SELECT, UPDATE ON TABLE "SIGMAmed"."MedicationAdherenceRecord" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."MedicalHistory" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."PatientSymptom" TO sigmamed_patient;
GRANT SELECT ON TABLE "SIGMAmed"."PatientSideEffect" TO sigmamed_patient;
GRANT SELECT, INSERT, UPDATE ON TABLE "SIGMAmed"."PatientReport" TO sigmamed_patient;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "SIGMAmed" TO sigmamed_patient;
GRANT USAGE ON SCHEMA "SIGMAmed" TO sigmamed_patient;

-- SECURITY HELPER FUNCTIONS
CREATE OR REPLACE FUNCTION "SIGMAmed".current_user_id()
RETURNS UUID AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_user_id', true), '')::UUID;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;
CREATE OR REPLACE FUNCTION "SIGMAmed".current_user_role()
RETURNS "SIGMAmed".user_role_enum AS $$
DECLARE
    user_role "SIGMAmed".user_role_enum;
BEGIN
    SELECT "Role" INTO user_role
    FROM "SIGMAmed"."User"
    WHERE "UserId" = "SIGMAmed".current_user_id();
    
    RETURN user_role;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION "SIGMAmed".current_user_institution()
RETURNS UUID AS $$
DECLARE
    institution_id UUID;
BEGIN
    SELECT "ClinicalInstitutionId" INTO institution_id
    FROM "SIGMAmed"."User"
    WHERE "UserId" = "SIGMAmed".current_user_id();
    
    RETURN institution_id;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION "SIGMAmed".is_patients_doctor(patient_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM "SIGMAmed"."PatientCareTeam"
        WHERE "DoctorId" = "SIGMAmed".current_user_id()
        AND "PatientId" = patient_id
        AND "IsActive" = true
        AND "IsDeleted" = false
    );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION "SIGMAmed".is_super_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM "SIGMAmed"."Admin" a
        JOIN "SIGMAmed"."User" u ON a."UserId" = u."UserId"
        WHERE u."UserId" = "SIGMAmed".current_user_id()
        AND a."AdminLevel" = 'super'
    );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION "SIGMAmed".is_hospital_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM "SIGMAmed"."Admin" a
        JOIN "SIGMAmed"."User" u ON a."UserId" = u."UserId"
        WHERE u."UserId" = "SIGMAmed".current_user_id()
        AND a."AdminLevel" = 'hospital'
    );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- ENABLE ROW-LEVEL SECURITY (FORCE ensures even table owners must obey RLS)

ALTER TABLE "SIGMAmed"."ClinicalInstitution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Admin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Doctor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Medication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PatientCareTeam" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Appointment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."AppointmentReminder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Prescription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PrescribedMedication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PrescribedMedicationSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."MedicationAdherenceRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."MedicalHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PatientSymptom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PatientSideEffect" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."PatientReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."AuditLog" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "SIGMAmed"."User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Admin" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Doctor" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Patient" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."Prescription" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."MedicalHistory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SIGMAmed"."AuditLog" FORCE ROW LEVEL SECURITY;

-- ROW-LEVEL SECURITY POLICIES

-- ClinicalInstitution
CREATE POLICY superadmin_clinicalinstitution_all ON "SIGMAmed"."ClinicalInstitution"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

-- Hospital Admin: Can only see and update their own institution
CREATE POLICY hospital_admin_clinicalinstitution_select ON "SIGMAmed"."ClinicalInstitution"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY hospital_admin_clinicalinstitution_update ON "SIGMAmed"."ClinicalInstitution"
    FOR UPDATE
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution())
    WITH CHECK ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY doctor_clinicalinstitution_select ON "SIGMAmed"."ClinicalInstitution"
    FOR SELECT
    TO sigmamed_doctor
    USING (true);

CREATE POLICY patient_clinicalinstitution_select ON "SIGMAmed"."ClinicalInstitution"
    FOR SELECT
    TO sigmamed_patient
    USING (true);

-- User
CREATE POLICY superadmin_user_all ON "SIGMAmed"."User"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

-- Hospital Admin: Can manage users in their institution
CREATE POLICY hospital_admin_user_select ON "SIGMAmed"."User"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY hospital_admin_user_insert ON "SIGMAmed"."User"
    FOR INSERT
    TO sigmamed_hospital_admin
    WITH CHECK ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY hospital_admin_user_update ON "SIGMAmed"."User"
    FOR UPDATE
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution())
    WITH CHECK ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY hospital_admin_user_delete ON "SIGMAmed"."User"
    FOR DELETE
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY doctor_user_select ON "SIGMAmed"."User"
    FOR SELECT
    TO sigmamed_doctor
    USING (
        "UserId" = "SIGMAmed".current_user_id() OR
        "SIGMAmed".is_patients_doctor("UserId")
    );

CREATE POLICY patient_user_select ON "SIGMAmed"."User"
    FOR SELECT
    TO sigmamed_patient
    USING ("UserId" = "SIGMAmed".current_user_id());

-- Admin
CREATE POLICY superadmin_admin_all ON "SIGMAmed"."Admin"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_admin_select ON "SIGMAmed"."Admin"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Admin"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_admin_insert ON "SIGMAmed"."Admin"
    FOR INSERT
    TO sigmamed_hospital_admin
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Admin"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_admin_update ON "SIGMAmed"."Admin"
    FOR UPDATE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Admin"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Admin"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_admin_delete ON "SIGMAmed"."Admin"
    FOR DELETE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Admin"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

-- Doctor
CREATE POLICY superadmin_doctor_all ON "SIGMAmed"."Doctor"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_doctor_select ON "SIGMAmed"."Doctor"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Doctor"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_doctor_insert ON "SIGMAmed"."Doctor"
    FOR INSERT
    TO sigmamed_hospital_admin
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Doctor"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_doctor_update ON "SIGMAmed"."Doctor"
    FOR UPDATE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Doctor"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Doctor"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_doctor_delete ON "SIGMAmed"."Doctor"
    FOR DELETE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Doctor"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_doctor_select ON "SIGMAmed"."Doctor"
    FOR SELECT
    TO sigmamed_doctor
    USING (
        "UserId" = "SIGMAmed".current_user_id() OR
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PatientCareTeam" pct1
            WHERE pct1."DoctorId" = "Doctor"."UserId"
            AND pct1."IsActive" = true
            AND pct1."IsDeleted" = false
            AND pct1."PatientId" IN (
                SELECT pct2."PatientId" FROM "SIGMAmed"."PatientCareTeam" pct2
                WHERE pct2."DoctorId" = "SIGMAmed".current_user_id()
                AND pct2."IsActive" = true
                AND pct2."IsDeleted" = false
            )
        )
    );

-- Patient
CREATE POLICY superadmin_patient_all ON "SIGMAmed"."Patient"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_patient_select ON "SIGMAmed"."Patient"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Patient"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_patient_insert ON "SIGMAmed"."Patient"
    FOR INSERT
    TO sigmamed_hospital_admin
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Patient"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_patient_update ON "SIGMAmed"."Patient"
    FOR UPDATE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Patient"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Patient"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY hospital_admin_patient_delete ON "SIGMAmed"."Patient"
    FOR DELETE
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Patient"."UserId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_patient_select ON "SIGMAmed"."Patient"
    FOR SELECT
    TO sigmamed_doctor
    USING ("SIGMAmed".is_patients_doctor("UserId"));

CREATE POLICY patient_patient_select ON "SIGMAmed"."Patient"
    FOR SELECT
    TO sigmamed_patient
    USING ("UserId" = "SIGMAmed".current_user_id());

-- Medication
CREATE POLICY superadmin_medication_all ON "SIGMAmed"."Medication"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

-- Hospital Admin: Full access to their institution's medications
CREATE POLICY hospital_admin_medication_all ON "SIGMAmed"."Medication"
    FOR ALL
    TO sigmamed_hospital_admin
    USING ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution())
    WITH CHECK ("ClinicalInstitutionId" = "SIGMAmed".current_user_institution());

CREATE POLICY doctor_medication_select ON "SIGMAmed"."Medication"
    FOR SELECT
    TO sigmamed_doctor
    USING (true);

CREATE POLICY patient_medication_select ON "SIGMAmed"."Medication"
    FOR SELECT
    TO sigmamed_patient
    USING (true);

-- PatientCareTeam
CREATE POLICY superadmin_careteam_all ON "SIGMAmed"."PatientCareTeam"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

-- Hospital Admin: Can manage care teams in their institution
CREATE POLICY hospital_admin_careteam_all ON "SIGMAmed"."PatientCareTeam"
    FOR ALL
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "PatientCareTeam"."DoctorId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "PatientCareTeam"."DoctorId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_careteam_all ON "SIGMAmed"."PatientCareTeam"
    FOR ALL
    TO sigmamed_doctor
    USING ("DoctorId" = "SIGMAmed".current_user_id())
    WITH CHECK ("DoctorId" = "SIGMAmed".current_user_id());

CREATE POLICY patient_careteam_select ON "SIGMAmed"."PatientCareTeam"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

-- Appointment
CREATE POLICY superadmin_appointment_all ON "SIGMAmed"."Appointment"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

-- Hospital Admin: Read-only for their institution
CREATE POLICY hospital_admin_appointment_select ON "SIGMAmed"."Appointment"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Appointment"."DoctorId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_appointment_all ON "SIGMAmed"."Appointment"
    FOR ALL
    TO sigmamed_doctor
    USING ("DoctorId" = "SIGMAmed".current_user_id())
    WITH CHECK ("DoctorId" = "SIGMAmed".current_user_id());

CREATE POLICY patient_appointment_select ON "SIGMAmed"."Appointment"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

-- AppointmentReminder
CREATE POLICY superadmin_appt_reminder_all ON "SIGMAmed"."AppointmentReminder"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_appt_reminder_select ON "SIGMAmed"."AppointmentReminder"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Appointment" a
            JOIN "SIGMAmed"."User" u ON a."DoctorId" = u."UserId"
            WHERE a."AppointmentId" = "AppointmentReminder"."AppointmentId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_appt_reminder_all ON "SIGMAmed"."AppointmentReminder"
    FOR ALL
    TO sigmamed_doctor
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Appointment" a
            WHERE a."AppointmentId" = "AppointmentReminder"."AppointmentId"
            AND a."DoctorId" = "SIGMAmed".current_user_id()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Appointment" a
            WHERE a."AppointmentId" = "AppointmentReminder"."AppointmentId"
            AND a."DoctorId" = "SIGMAmed".current_user_id()
        )
    );

CREATE POLICY patient_appt_reminder_select ON "SIGMAmed"."AppointmentReminder"
    FOR SELECT
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Appointment" a
            WHERE a."AppointmentId" = "AppointmentReminder"."AppointmentId"
            AND a."PatientId" = "SIGMAmed".current_user_id()
        )
    );

-- Prescription
CREATE POLICY superadmin_prescription_all ON "SIGMAmed"."Prescription"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_prescription_select ON "SIGMAmed"."Prescription"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "Prescription"."DoctorId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_prescription_all ON "SIGMAmed"."Prescription"
    FOR ALL
    TO sigmamed_doctor
    USING ("SIGMAmed".is_patients_doctor("PatientId"))
    WITH CHECK ("SIGMAmed".is_patients_doctor("PatientId"));

CREATE POLICY patient_prescription_select ON "SIGMAmed"."Prescription"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

-- PrescribedMedication
CREATE POLICY superadmin_prescribed_med_all ON "SIGMAmed"."PrescribedMedication"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_prescribed_med_select ON "SIGMAmed"."PrescribedMedication"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Prescription" p
            JOIN "SIGMAmed"."User" u ON p."DoctorId" = u."UserId"
            WHERE p."PrescriptionId" = "PrescribedMedication"."PrescriptionId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_prescribed_med_all ON "SIGMAmed"."PrescribedMedication"
    FOR ALL
    TO sigmamed_doctor
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Prescription" p
            WHERE p."PrescriptionId" = "PrescribedMedication"."PrescriptionId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Prescription" p
            WHERE p."PrescriptionId" = "PrescribedMedication"."PrescriptionId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    );

CREATE POLICY patient_prescribed_med_select ON "SIGMAmed"."PrescribedMedication"
    FOR SELECT
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Prescription" p
            WHERE p."PrescriptionId" = "PrescribedMedication"."PrescriptionId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

-- PrescribedMedicationSchedule
CREATE POLICY superadmin_med_schedule_all ON "SIGMAmed"."PrescribedMedicationSchedule"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_med_schedule_select ON "SIGMAmed"."PrescribedMedicationSchedule"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            JOIN "SIGMAmed"."User" u ON p."DoctorId" = u."UserId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_med_schedule_all ON "SIGMAmed"."PrescribedMedicationSchedule"
    FOR ALL
    TO sigmamed_doctor
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    );

CREATE POLICY patient_med_schedule_select ON "SIGMAmed"."PrescribedMedicationSchedule"
    FOR SELECT
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

CREATE POLICY patient_med_schedule_update ON "SIGMAmed"."PrescribedMedicationSchedule"
    FOR UPDATE
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PrescribedMedicationSchedule"."PrescribedMedicationId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

-- MedicationAdherenceRecord
CREATE POLICY superadmin_adherence_all ON "SIGMAmed"."MedicationAdherenceRecord"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_adherence_select ON "SIGMAmed"."MedicationAdherenceRecord"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            JOIN "SIGMAmed"."User" u ON p."DoctorId" = u."UserId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_adherence_all ON "SIGMAmed"."MedicationAdherenceRecord"
    FOR ALL
    TO sigmamed_doctor
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    );

CREATE POLICY patient_adherence_select ON "SIGMAmed"."MedicationAdherenceRecord"
    FOR SELECT
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

CREATE POLICY patient_adherence_update ON "SIGMAmed"."MedicationAdherenceRecord"
    FOR UPDATE
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedicationSchedule" pms
            JOIN "SIGMAmed"."PrescribedMedication" pm ON pms."PrescribedMedicationId" = pm."PrescribedMedicationId"
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pms."PrescribedMedicationScheduleId" = "MedicationAdherenceRecord"."PrescribedMedicationScheduleId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

-- MedicalHistory
CREATE POLICY superadmin_medical_history_all ON "SIGMAmed"."MedicalHistory"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_medical_history_select ON "SIGMAmed"."MedicalHistory"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "MedicalHistory"."PatientId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_medical_history_all ON "SIGMAmed"."MedicalHistory"
    FOR ALL
    TO sigmamed_doctor
    USING ("SIGMAmed".is_patients_doctor("PatientId"))
    WITH CHECK ("SIGMAmed".is_patients_doctor("PatientId"));

CREATE POLICY patient_medical_history_select ON "SIGMAmed"."MedicalHistory"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

-- PatientSymptom
CREATE POLICY superadmin_symptom_all ON "SIGMAmed"."PatientSymptom"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_symptom_select ON "SIGMAmed"."PatientSymptom"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "PatientSymptom"."PatientId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_symptom_all ON "SIGMAmed"."PatientSymptom"
    FOR ALL
    TO sigmamed_doctor
    USING ("SIGMAmed".is_patients_doctor("PatientId"))
    WITH CHECK ("SIGMAmed".is_patients_doctor("PatientId"));

CREATE POLICY patient_symptom_select ON "SIGMAmed"."PatientSymptom"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

-- PatientSideEffect
CREATE POLICY superadmin_side_effect_all ON "SIGMAmed"."PatientSideEffect"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_side_effect_select ON "SIGMAmed"."PatientSideEffect"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            JOIN "SIGMAmed"."User" u ON p."DoctorId" = u."UserId"
            WHERE pm."PrescribedMedicationId" = "PatientSideEffect"."PrescribedMedicationId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_side_effect_all ON "SIGMAmed"."PatientSideEffect"
    FOR ALL
    TO sigmamed_doctor
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PatientSideEffect"."PrescribedMedicationId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PatientSideEffect"."PrescribedMedicationId"
            AND "SIGMAmed".is_patients_doctor(p."PatientId")
        )
    );

CREATE POLICY patient_side_effect_select ON "SIGMAmed"."PatientSideEffect"
    FOR SELECT
    TO sigmamed_patient
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."PrescribedMedication" pm
            JOIN "SIGMAmed"."Prescription" p ON pm."PrescriptionId" = p."PrescriptionId"
            WHERE pm."PrescribedMedicationId" = "PatientSideEffect"."PrescribedMedicationId"
            AND p."PatientId" = "SIGMAmed".current_user_id()
        )
    );

-- PatientReport
CREATE POLICY superadmin_report_all ON "SIGMAmed"."PatientReport"
    FOR ALL
    TO sigmamed_superadmin
    USING (true)
    WITH CHECK (true);

CREATE POLICY hospital_admin_report_select ON "SIGMAmed"."PatientReport"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "PatientReport"."DoctorId"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_report_all ON "SIGMAmed"."PatientReport"
    FOR ALL
    TO sigmamed_doctor
    USING ("SIGMAmed".is_patients_doctor("PatientId"))
    WITH CHECK ("SIGMAmed".is_patients_doctor("PatientId"));

CREATE POLICY patient_report_select ON "SIGMAmed"."PatientReport"
    FOR SELECT
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id());

CREATE POLICY patient_report_insert ON "SIGMAmed"."PatientReport"
    FOR INSERT
    TO sigmamed_patient
    WITH CHECK ("PatientId" = "SIGMAmed".current_user_id());

CREATE POLICY patient_report_update ON "SIGMAmed"."PatientReport"
    FOR UPDATE
    TO sigmamed_patient
    USING ("PatientId" = "SIGMAmed".current_user_id())
    WITH CHECK ("PatientId" = "SIGMAmed".current_user_id());

-- AuditLog
CREATE POLICY superadmin_audit_all ON "SIGMAmed"."AuditLog"
    FOR SELECT
    TO sigmamed_superadmin
    USING (true);

CREATE POLICY hospital_admin_audit_select ON "SIGMAmed"."AuditLog"
    FOR SELECT
    TO sigmamed_hospital_admin
    USING (
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."User" u
            WHERE u."UserId" = "AuditLog"."ActedBy"
            AND u."ClinicalInstitutionId" = "SIGMAmed".current_user_institution()
        )
    );

CREATE POLICY doctor_audit_select ON "SIGMAmed"."AuditLog"
    FOR SELECT
    TO sigmamed_doctor
    USING (
        "ActedBy" = "SIGMAmed".current_user_id() OR
        EXISTS (
            SELECT 1 FROM "SIGMAmed"."Patient" p
            WHERE p."UserId" = "AuditLog"."RecordId"
            AND "SIGMAmed".is_patients_doctor(p."UserId")
        )
    );

-- View 

-- Audit log
CREATE OR REPLACE VIEW "SIGMAmed"."AuditLogView" AS
SELECT
    A."AuditLogId",
    A."ActionTimestamp",
    A."TableName",
    A."RecordId",
    A."ActionStatus",
    U."FirstName" || ' ' || U."LastName" AS "ActedByFullName", -- Display full name
    U."Username" AS "ActedByUsername",
    U."Role" AS "ActedByRole",
    A."OldValue",
    A."NewValue"
FROM
    "SIGMAmed"."AuditLog" A
JOIN
    "SIGMAmed"."User" U ON A."ActedBy" = U."UserId"
ORDER BY
    A."ActionTimestamp" DESC;

COMMENT ON VIEW "SIGMAmed"."AuditLogView" IS 'Provides a human-readable view of the audit trail, joining the ActedBy UUID to the user''s name and role.';

-- Create the view of medical history with patient symptom
CREATE OR REPLACE VIEW "SIGMAmed"."PatientMedicalHistoryView" AS
SELECT
	U."FirstName",
	U."LastName",
	MH."DiseaseName",
	MH."Severity" AS "DiseaseSeverity",
	MH."DiagnosedDate",
	MH."ResolutionDate" AS "DiseaseResolution",
	PS."SymptomName",
    PS."Severity" AS "SymptomSeverity",
    PS."OnsetDate",
    PS."ResolutionDate" AS "SymptomResolution"
FROM
	"SIGMAmed"."MedicalHistory" AS MH
	INNER JOIN "SIGMAmed"."User" AS U ON U."UserId" = MH."PatientId"
	INNER JOIN "SIGMAmed"."PatientSymptom" AS PS ON MH."MedicalHistoryId" = PS."MedicalHistoryId"
WHERE
	MH."IsDeleted" = FALSE;


-- Create the view of patient's prescription 
CREATE OR REPLACE VIEW "SIGMAmed"."PatientPrescriptionsView" AS
SELECT 
    U."FirstName", 
    U."LastName", 
    P."Status" AS "Prescription Status",
    P."PrescribedDate" AS "Prescription Prescribed Date",
    P."ExpiryDate",
    PM."MedicationNameSnapshot",
    PM."DosageAmountPrescribed",
    PM."DosePerTime",
    PM."Status" AS "Prescribed Medication Status",
    PM."DefaultDayMask",
    PM."PrescribedDate" AS "Medication Prescribed Date",
    PM."TimesPerDay",
    PSE."SideEffectName",
    PSE."Severity",
    PSE."OnsetDate",
    PSE."ResolutionDate"
FROM "SIGMAmed"."Prescription" AS P
INNER JOIN "SIGMAmed"."PrescribedMedication" AS PM
    ON P."PrescriptionId" = PM."PrescriptionId"
INNER JOIN "SIGMAmed"."User" AS U
    ON P."PatientId" = U."UserId"
INNER JOIN "SIGMAmed"."PatientSideEffect" AS PSE
    ON PM."PrescribedMedicationId" = PSE."PrescribedMedicationId"
WHERE P."IsDeleted" = FALSE;

-- -- Create the view of all MedicationAdherenceRecord
CREATE OR REPLACE VIEW "SIGMAmed"."PatientAdherenceRecordView" AS
SELECT
	U."UserId",
	U."FirstName",
	U."LastName",
	PM."MedicationId",
	PM."DosePerTime",
	M."MedicationName",
	P."PrescriptionNumber",
	MAR."ScheduledTime",
	MAR."DoseQuantity",
	MAR."CurrentStatus",
	MAR."ActionTime"
FROM "SIGMAmed"."MedicationAdherenceRecord" AS MAR
INNER JOIN "SIGMAmed"."PrescribedMedicationSchedule" AS PMS 
	ON MAR."PrescribedMedicationScheduleId" = PMS."PrescribedMedicationScheduleId"
INNER JOIN "SIGMAmed"."PrescribedMedication" AS PM 
	ON PMS."PrescribedMedicationId" = PM."PrescribedMedicationId"
INNER JOIN "SIGMAmed"."Medication" AS M 
	ON PM."MedicationId" = M."MedicationId"
INNER JOIN "SIGMAmed"."Prescription" AS P 
	ON PM."PrescriptionId" = P."PrescriptionId"
INNER JOIN "SIGMAmed"."User" AS U 
	ON P."PatientId" = U."UserId"
WHERE PM."IsDeleted" = FALSE 
  AND P."IsDeleted" = FALSE 
  AND U."IsDeleted" = FALSE;


-- ClinicalInstitution Indexes
CREATE INDEX idx_clinical_institution_name ON "SIGMAmed"."ClinicalInstitution"("ClinicalInstitutionName") WHERE "IsDeleted" = FALSE;

-- User Indexes
CREATE INDEX idx_user_ic_passport ON "SIGMAmed"."User"("ICPassportNumber") WHERE "IsDeleted" = FALSE;

-- Medication Indexes
CREATE INDEX idx_medication_name ON "SIGMAmed"."Medication"("MedicationName") WHERE "IsDeleted" = FALSE;

-- Prescription Indexes
CREATE INDEX idx_prescription_number ON "SIGMAmed"."Prescription"("PrescriptionNumber") WHERE "IsDeleted" = FALSE; 
CREATE INDEX idx_prescription_patient_date ON "SIGMAmed"."Prescription"("PatientId","PrescribedDate") WHERE "IsDeleted" = FALSE; 

-- PrescribedMedication Indexes 
CREATE INDEX idx_prescribed_medication_prescription ON "SIGMAmed"."PrescribedMedication"("PrescriptionId") WHERE "IsDeleted" = FALSE;
CREATE INDEX idx_prescribed_medication_status ON "SIGMAmed"."PrescribedMedication"("MedicationId","PrescriptionId","Status") WHERE "IsDeleted" = FALSE;

-- MedicationAdherenceRecord Indexes
CREATE INDEX idx_adherence_schedule ON "SIGMAmed"."MedicationAdherenceRecord"("ScheduledTime", "PrescribedMedicationScheduleId");

-- PrescribedMedicationSchedule Indexes
CREATE INDEX idx_prescribed_schedule_medication ON "SIGMAmed"."PrescribedMedicationSchedule"("PrescribedMedicationId"); 

-- PatientReport Indexes
CREATE INDEX idx_report_patient_time ON "SIGMAmed"."PatientReport"("PatientId","CreatedAt") WHERE "IsDeleted" = FALSE;
CREATE INDEX idx_report_doctor ON "SIGMAmed"."PatientReport"("DoctorId") WHERE "IsDeleted" = FALSE;

-- PatientCareTeam Indexes
CREATE INDEX idx_care_patient ON "SIGMAmed"."PatientCareTeam"("PatientId","IsActive") WHERE "IsDeleted" = FALSE;

-- Appointment Indexes
CREATE INDEX idx_appointment_patient_date ON "SIGMAmed"."Appointment"("PatientId","AppointmentDate") WHERE "IsDeleted" = FALSE;
CREATE INDEX idx_appointment_doctor ON "SIGMAmed"."Appointment"("DoctorId") WHERE "IsDeleted" = FALSE;

-- AppointmentReminder Indexes
CREATE INDEX idx_appointment_reminder_appointment ON "SIGMAmed"."AppointmentReminder"("AppointmentId");

-- MedicalHistory Indexes
CREATE INDEX idx_medical_history_patient ON "SIGMAmed"."MedicalHistory"("PatientId") WHERE "IsDeleted" = FALSE;

-- PatientSymptom Indexes
CREATE INDEX idx_patient_symptoms_medical_history ON "SIGMAmed"."PatientSymptom"("MedicalHistoryId") WHERE "IsDeleted" = FALSE;


